<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

/**
 * Referentiel des pays (ISO 3166-1, noms francais) : liste complete et
 * statique (250 entrees), alignee sur la meme source que le frontend
 * (`i18n-iso-countries`, locale `fr`, `getNames('fr')` sans option
 * `select`) pour garantir des noms identiques cote backend et cote
 * frontend (voir `src/lib/countries.ts` : `countryNameFr()`).
 *
 * Idempotent : `updateOrCreate` sur `iso_code` (colonne unique), donc
 * rejouable sans creer de doublons ni ecraser un `id` deja reference par
 * une commande/fournisseur/client/produit existant.
 *
 * Lancer avec : php artisan db:seed --class=CountrySeeder
 */
class CountrySeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        foreach (self::COUNTRIES as $country) {
            Country::query()->updateOrCreate(
                ['iso_code' => $country['iso_code']],
                ['name' => $country['name'], 'is_active' => true],
            );
        }
    }

    /** @var array<int, array{iso_code: string, name: string}> */
    private const COUNTRIES = [
            ['iso_code' => 'AD', 'name' => 'Andorre'],
            ['iso_code' => 'AE', 'name' => 'Émirats Arabes Unis'],
            ['iso_code' => 'AF', 'name' => 'Afghanistan'],
            ['iso_code' => 'AG', 'name' => 'Antigua-et-Barbuda'],
            ['iso_code' => 'AI', 'name' => 'Anguilla'],
            ['iso_code' => 'AL', 'name' => 'Albanie'],
            ['iso_code' => 'AM', 'name' => 'Arménie'],
            ['iso_code' => 'AO', 'name' => 'Angola'],
            ['iso_code' => 'AQ', 'name' => 'Antarctique'],
            ['iso_code' => 'AR', 'name' => 'Argentine'],
            ['iso_code' => 'AS', 'name' => 'Samoa américaines'],
            ['iso_code' => 'AT', 'name' => 'Autriche'],
            ['iso_code' => 'AU', 'name' => 'Australie'],
            ['iso_code' => 'AW', 'name' => 'Aruba'],
            ['iso_code' => 'AX', 'name' => 'Åland'],
            ['iso_code' => 'AZ', 'name' => 'Azerbaïdjan'],
            ['iso_code' => 'BA', 'name' => 'Bosnie-Herzégovine'],
            ['iso_code' => 'BB', 'name' => 'Barbade'],
            ['iso_code' => 'BD', 'name' => 'Bangladesh'],
            ['iso_code' => 'BE', 'name' => 'Belgique'],
            ['iso_code' => 'BF', 'name' => 'Burkina Faso'],
            ['iso_code' => 'BG', 'name' => 'Bulgarie'],
            ['iso_code' => 'BH', 'name' => 'Bahreïn'],
            ['iso_code' => 'BI', 'name' => 'Burundi'],
            ['iso_code' => 'BJ', 'name' => 'Bénin'],
            ['iso_code' => 'BL', 'name' => 'Saint-Barthélemy'],
            ['iso_code' => 'BM', 'name' => 'Bermudes'],
            ['iso_code' => 'BN', 'name' => 'Brunei Darussalam'],
            ['iso_code' => 'BO', 'name' => 'Bolivie'],
            ['iso_code' => 'BQ', 'name' => 'Bonaire, Saint-Eustache et Saba'],
            ['iso_code' => 'BR', 'name' => 'Brésil'],
            ['iso_code' => 'BS', 'name' => 'Bahamas'],
            ['iso_code' => 'BT', 'name' => 'Bhoutan'],
            ['iso_code' => 'BV', 'name' => 'Île Bouvet'],
            ['iso_code' => 'BW', 'name' => 'Botswana'],
            ['iso_code' => 'BY', 'name' => 'Biélorussie'],
            ['iso_code' => 'BZ', 'name' => 'Belize'],
            ['iso_code' => 'CA', 'name' => 'Canada'],
            ['iso_code' => 'CC', 'name' => 'Îles Cocos'],
            ['iso_code' => 'CD', 'name' => 'République démocratique du Congo'],
            ['iso_code' => 'CF', 'name' => 'République Centrafricaine'],
            ['iso_code' => 'CG', 'name' => 'République du Congo'],
            ['iso_code' => 'CH', 'name' => 'Suisse'],
            ['iso_code' => 'CI', 'name' => 'Côte-d\'Ivoire'],
            ['iso_code' => 'CK', 'name' => 'Îles Cook'],
            ['iso_code' => 'CL', 'name' => 'Chili'],
            ['iso_code' => 'CM', 'name' => 'Cameroun'],
            ['iso_code' => 'CN', 'name' => 'Chine'],
            ['iso_code' => 'CO', 'name' => 'Colombie'],
            ['iso_code' => 'CR', 'name' => 'Costa Rica'],
            ['iso_code' => 'CU', 'name' => 'Cuba'],
            ['iso_code' => 'CV', 'name' => 'Cap-Vert'],
            ['iso_code' => 'CW', 'name' => 'Curaçao'],
            ['iso_code' => 'CX', 'name' => 'Île Christmas'],
            ['iso_code' => 'CY', 'name' => 'Chypre'],
            ['iso_code' => 'CZ', 'name' => 'République Tchèque'],
            ['iso_code' => 'DE', 'name' => 'Allemagne'],
            ['iso_code' => 'DJ', 'name' => 'Djibouti'],
            ['iso_code' => 'DK', 'name' => 'Danemark'],
            ['iso_code' => 'DM', 'name' => 'Dominique'],
            ['iso_code' => 'DO', 'name' => 'République Dominicaine'],
            ['iso_code' => 'DZ', 'name' => 'Algérie'],
            ['iso_code' => 'EC', 'name' => 'Équateur'],
            ['iso_code' => 'EE', 'name' => 'Estonie'],
            ['iso_code' => 'EG', 'name' => 'Égypte'],
            ['iso_code' => 'EH', 'name' => 'Sahara occidental'],
            ['iso_code' => 'ER', 'name' => 'Érythrée'],
            ['iso_code' => 'ES', 'name' => 'Espagne'],
            ['iso_code' => 'ET', 'name' => 'Éthiopie'],
            ['iso_code' => 'FI', 'name' => 'Finlande'],
            ['iso_code' => 'FJ', 'name' => 'Fidji'],
            ['iso_code' => 'FK', 'name' => 'Îles Malouines'],
            ['iso_code' => 'FM', 'name' => 'Micronésie'],
            ['iso_code' => 'FO', 'name' => 'Îles Féroé'],
            ['iso_code' => 'FR', 'name' => 'France'],
            ['iso_code' => 'GA', 'name' => 'Gabon'],
            ['iso_code' => 'GB', 'name' => 'Royaume-Uni'],
            ['iso_code' => 'GD', 'name' => 'Grenade'],
            ['iso_code' => 'GE', 'name' => 'Géorgie'],
            ['iso_code' => 'GF', 'name' => 'Guyane française'],
            ['iso_code' => 'GG', 'name' => 'Guernesey'],
            ['iso_code' => 'GH', 'name' => 'Ghana'],
            ['iso_code' => 'GI', 'name' => 'Gibraltar'],
            ['iso_code' => 'GL', 'name' => 'Groenland'],
            ['iso_code' => 'GM', 'name' => 'Gambie'],
            ['iso_code' => 'GN', 'name' => 'Guinée'],
            ['iso_code' => 'GP', 'name' => 'Guadeloupe'],
            ['iso_code' => 'GQ', 'name' => 'Guinée équatoriale'],
            ['iso_code' => 'GR', 'name' => 'Grèce'],
            ['iso_code' => 'GS', 'name' => 'Géorgie du Sud-et-les Îles Sandwich du Sud'],
            ['iso_code' => 'GT', 'name' => 'Guatemala'],
            ['iso_code' => 'GU', 'name' => 'Guam'],
            ['iso_code' => 'GW', 'name' => 'Guinée-Bissau'],
            ['iso_code' => 'GY', 'name' => 'Guyana'],
            ['iso_code' => 'HK', 'name' => 'Hong Kong'],
            ['iso_code' => 'HM', 'name' => 'Îles Heard-et-MacDonald'],
            ['iso_code' => 'HN', 'name' => 'Honduras'],
            ['iso_code' => 'HR', 'name' => 'Croatie'],
            ['iso_code' => 'HT', 'name' => 'Haïti'],
            ['iso_code' => 'HU', 'name' => 'Hongrie'],
            ['iso_code' => 'ID', 'name' => 'Indonésie'],
            ['iso_code' => 'IE', 'name' => 'Irlande'],
            ['iso_code' => 'IL', 'name' => 'Israël'],
            ['iso_code' => 'IM', 'name' => 'Île de Man'],
            ['iso_code' => 'IN', 'name' => 'Inde'],
            ['iso_code' => 'IO', 'name' => 'Océan Indien Britannique'],
            ['iso_code' => 'IQ', 'name' => 'Irak'],
            ['iso_code' => 'IR', 'name' => 'Iran'],
            ['iso_code' => 'IS', 'name' => 'Islande'],
            ['iso_code' => 'IT', 'name' => 'Italie'],
            ['iso_code' => 'JE', 'name' => 'Jersey'],
            ['iso_code' => 'JM', 'name' => 'Jamaïque'],
            ['iso_code' => 'JO', 'name' => 'Jordanie'],
            ['iso_code' => 'JP', 'name' => 'Japon'],
            ['iso_code' => 'KE', 'name' => 'Kenya'],
            ['iso_code' => 'KG', 'name' => 'Kirghizistan'],
            ['iso_code' => 'KH', 'name' => 'Cambodge'],
            ['iso_code' => 'KI', 'name' => 'Kiribati'],
            ['iso_code' => 'KM', 'name' => 'Comores'],
            ['iso_code' => 'KN', 'name' => 'Saint-Christophe-et-Niévès'],
            ['iso_code' => 'KP', 'name' => 'Corée du Nord'],
            ['iso_code' => 'KR', 'name' => 'Corée du Sud'],
            ['iso_code' => 'KW', 'name' => 'Koweït'],
            ['iso_code' => 'KY', 'name' => 'Îles Caïmans'],
            ['iso_code' => 'KZ', 'name' => 'Kazakhstan'],
            ['iso_code' => 'LA', 'name' => 'Laos'],
            ['iso_code' => 'LB', 'name' => 'Liban'],
            ['iso_code' => 'LC', 'name' => 'Sainte-Lucie'],
            ['iso_code' => 'LI', 'name' => 'Liechtenstein'],
            ['iso_code' => 'LK', 'name' => 'Sri Lanka'],
            ['iso_code' => 'LR', 'name' => 'Libéria'],
            ['iso_code' => 'LS', 'name' => 'Lesotho'],
            ['iso_code' => 'LT', 'name' => 'Lituanie'],
            ['iso_code' => 'LU', 'name' => 'Luxembourg'],
            ['iso_code' => 'LV', 'name' => 'Lettonie'],
            ['iso_code' => 'LY', 'name' => 'Libye'],
            ['iso_code' => 'MA', 'name' => 'Maroc'],
            ['iso_code' => 'MC', 'name' => 'Monaco'],
            ['iso_code' => 'MD', 'name' => 'Moldavie'],
            ['iso_code' => 'ME', 'name' => 'Monténégro'],
            ['iso_code' => 'MF', 'name' => 'Saint-Martin (partie française)'],
            ['iso_code' => 'MG', 'name' => 'Madagascar'],
            ['iso_code' => 'MH', 'name' => 'Îles Marshall'],
            ['iso_code' => 'MK', 'name' => 'Macédoine du Nord'],
            ['iso_code' => 'ML', 'name' => 'Mali'],
            ['iso_code' => 'MM', 'name' => 'Myanmar'],
            ['iso_code' => 'MN', 'name' => 'Mongolie'],
            ['iso_code' => 'MO', 'name' => 'Macao'],
            ['iso_code' => 'MP', 'name' => 'Îles Mariannes du Nord'],
            ['iso_code' => 'MQ', 'name' => 'Martinique'],
            ['iso_code' => 'MR', 'name' => 'Mauritanie'],
            ['iso_code' => 'MS', 'name' => 'Montserrat'],
            ['iso_code' => 'MT', 'name' => 'Malte'],
            ['iso_code' => 'MU', 'name' => 'Maurice'],
            ['iso_code' => 'MV', 'name' => 'Maldives'],
            ['iso_code' => 'MW', 'name' => 'Malawi'],
            ['iso_code' => 'MX', 'name' => 'Mexique'],
            ['iso_code' => 'MY', 'name' => 'Malaisie'],
            ['iso_code' => 'MZ', 'name' => 'Mozambique'],
            ['iso_code' => 'NA', 'name' => 'Namibie'],
            ['iso_code' => 'NC', 'name' => 'Nouvelle-Calédonie'],
            ['iso_code' => 'NE', 'name' => 'Niger'],
            ['iso_code' => 'NF', 'name' => 'Île Norfolk'],
            ['iso_code' => 'NG', 'name' => 'Nigéria'],
            ['iso_code' => 'NI', 'name' => 'Nicaragua'],
            ['iso_code' => 'NL', 'name' => 'Pays-Bas'],
            ['iso_code' => 'NO', 'name' => 'Norvège'],
            ['iso_code' => 'NP', 'name' => 'Népal'],
            ['iso_code' => 'NR', 'name' => 'Nauru'],
            ['iso_code' => 'NU', 'name' => 'Niué'],
            ['iso_code' => 'NZ', 'name' => 'Nouvelle-Zélande'],
            ['iso_code' => 'OM', 'name' => 'Oman'],
            ['iso_code' => 'PA', 'name' => 'Panama'],
            ['iso_code' => 'PE', 'name' => 'Pérou'],
            ['iso_code' => 'PF', 'name' => 'Polynésie française'],
            ['iso_code' => 'PG', 'name' => 'Papouasie-Nouvelle-Guinée'],
            ['iso_code' => 'PH', 'name' => 'Philippines'],
            ['iso_code' => 'PK', 'name' => 'Pakistan'],
            ['iso_code' => 'PL', 'name' => 'Pologne'],
            ['iso_code' => 'PM', 'name' => 'Saint-Pierre-et-Miquelon'],
            ['iso_code' => 'PN', 'name' => 'Îles Pitcairn'],
            ['iso_code' => 'PR', 'name' => 'Porto Rico'],
            ['iso_code' => 'PS', 'name' => 'Palestine'],
            ['iso_code' => 'PT', 'name' => 'Portugal'],
            ['iso_code' => 'PW', 'name' => 'Palaos'],
            ['iso_code' => 'PY', 'name' => 'Paraguay'],
            ['iso_code' => 'QA', 'name' => 'Qatar'],
            ['iso_code' => 'RE', 'name' => 'Réunion'],
            ['iso_code' => 'RO', 'name' => 'Roumanie'],
            ['iso_code' => 'RS', 'name' => 'Serbie'],
            ['iso_code' => 'RU', 'name' => 'Russie'],
            ['iso_code' => 'RW', 'name' => 'Rwanda'],
            ['iso_code' => 'SA', 'name' => 'Arabie Saoudite'],
            ['iso_code' => 'SB', 'name' => 'Îles Salomon'],
            ['iso_code' => 'SC', 'name' => 'Seychelles'],
            ['iso_code' => 'SD', 'name' => 'Soudan'],
            ['iso_code' => 'SE', 'name' => 'Suède'],
            ['iso_code' => 'SG', 'name' => 'Singapour'],
            ['iso_code' => 'SH', 'name' => 'Sainte-Hélène'],
            ['iso_code' => 'SI', 'name' => 'Slovénie'],
            ['iso_code' => 'SJ', 'name' => 'Svalbard et Île Jan Mayen'],
            ['iso_code' => 'SK', 'name' => 'Slovaquie'],
            ['iso_code' => 'SL', 'name' => 'Sierra Leone'],
            ['iso_code' => 'SM', 'name' => 'Saint-Marin'],
            ['iso_code' => 'SN', 'name' => 'Sénégal'],
            ['iso_code' => 'SO', 'name' => 'Somalie'],
            ['iso_code' => 'SR', 'name' => 'Suriname'],
            ['iso_code' => 'SS', 'name' => 'Soudan du Sud'],
            ['iso_code' => 'ST', 'name' => 'São Tomé-et-Principe'],
            ['iso_code' => 'SV', 'name' => 'El Salvador'],
            ['iso_code' => 'SX', 'name' => 'Saint-Martin (partie néerlandaise)'],
            ['iso_code' => 'SY', 'name' => 'Syrie'],
            ['iso_code' => 'SZ', 'name' => 'Royaume d\'Eswatini'],
            ['iso_code' => 'TC', 'name' => 'Îles Turques-et-Caïques'],
            ['iso_code' => 'TD', 'name' => 'Tchad'],
            ['iso_code' => 'TF', 'name' => 'Terres australes françaises'],
            ['iso_code' => 'TG', 'name' => 'Togo'],
            ['iso_code' => 'TH', 'name' => 'Thaïlande'],
            ['iso_code' => 'TJ', 'name' => 'Tadjikistan'],
            ['iso_code' => 'TK', 'name' => 'Tokelau'],
            ['iso_code' => 'TL', 'name' => 'Timor-Leste'],
            ['iso_code' => 'TM', 'name' => 'Turkménistan'],
            ['iso_code' => 'TN', 'name' => 'Tunisie'],
            ['iso_code' => 'TO', 'name' => 'Tonga'],
            ['iso_code' => 'TR', 'name' => 'Turquie'],
            ['iso_code' => 'TT', 'name' => 'Trinité-et-Tobago'],
            ['iso_code' => 'TV', 'name' => 'Tuvalu'],
            ['iso_code' => 'TW', 'name' => 'Taïwan'],
            ['iso_code' => 'TZ', 'name' => 'République unie de Tanzanie'],
            ['iso_code' => 'UA', 'name' => 'Ukraine'],
            ['iso_code' => 'UG', 'name' => 'Ouganda'],
            ['iso_code' => 'UM', 'name' => 'Îles mineures éloignées des États-Unis'],
            ['iso_code' => 'US', 'name' => 'États-Unis d\'Amérique'],
            ['iso_code' => 'UY', 'name' => 'Uruguay'],
            ['iso_code' => 'UZ', 'name' => 'Ouzbékistan'],
            ['iso_code' => 'VA', 'name' => 'Saint-Siège (Vatican)'],
            ['iso_code' => 'VC', 'name' => 'Saint-Vincent-et-les-Grenadines'],
            ['iso_code' => 'VE', 'name' => 'Venezuela'],
            ['iso_code' => 'VG', 'name' => 'Îles vierges britanniques'],
            ['iso_code' => 'VI', 'name' => 'Îles vierges américaines'],
            ['iso_code' => 'VN', 'name' => 'Vietnam'],
            ['iso_code' => 'VU', 'name' => 'Vanuatu'],
            ['iso_code' => 'WF', 'name' => 'Wallis-et-Futuna'],
            ['iso_code' => 'WS', 'name' => 'Samoa'],
            ['iso_code' => 'XK', 'name' => 'Kosovo'],
            ['iso_code' => 'YE', 'name' => 'Yémen'],
            ['iso_code' => 'YT', 'name' => 'Mayotte'],
            ['iso_code' => 'ZA', 'name' => 'Afrique du Sud'],
            ['iso_code' => 'ZM', 'name' => 'Zambie'],
            ['iso_code' => 'ZW', 'name' => 'Zimbabwe'],
    ];
}
