<?php

// English labels for the issued PDF documents (proforma, invoice, credit note,
// receipt, comparison). Rendering language is driven by `invoices.language`
// (DocumentLanguage enum, FR/EN), derived from `clients.preferred_language` or
// an explicit choice at emission. See Doc/documents_bilingues_addendum.md.

return [

    'meta' => [
        'generated_by' => 'Document generated by the NJ Global Trade platform',
        'page' => 'page',
        'comparatif_suffix' => 'comparison',
    ],

    'common' => [
        'reference' => 'Reference',
        'issue_date' => 'Issue date',
        'valid_until' => 'Valid until',
        'issued_by' => 'Issued by',
        'billed_to' => 'Billed to',
        'received_from' => 'Received from',
        'billing_mode' => 'Billing mode',
        'linked_order' => 'Linked order',
    ],

    'billing_mode' => [
        'COMMISSION_VISIBLE' => 'Commission shown',
        'PRIX_GLOBAL' => 'All-in price',
    ],

    'items' => [
        'designation' => 'Description',
        'quantity' => 'Quantity',
        'unit_price' => 'Unit price',
        'subtotal' => 'Subtotal',
        'goods_subtotal' => 'Goods subtotal',
        'credited_subtotal' => 'Credited subtotal',
    ],

    'section' => [
        'order_detail' => 'Order details',
        'credit_detail' => 'Credit note details',
        'settled_order_detail' => 'Settled order details',
        'transport' => 'Shipping',
        'financial_summary' => 'Financial summary',
        'summary' => 'Summary',
        'payment_methods' => 'Accepted payment methods',
        'payment_detail' => 'Payment details',
    ],

    'transport' => [
        'mode' => 'Mode',
        'est_weight' => 'Estimated weight',
        'est_volume' => 'Estimated volume',
        'lead_time' => 'Indicative lead time',
        'note' => 'Weights and volumes are indicative, within a ±10 to 15% margin — final values confirmed at shipment.',
        'AERIEN_STANDARD' => 'Standard air freight',
        'AERIEN_SENSIBLE' => 'Sensitive air freight',
        'MARITIME' => 'Sea freight',
        'NON_APPLICABLE' => 'Not applicable',
        'delay' => [
            'AERIEN_STANDARD' => '7 to 14 days',
            'AERIEN_SENSIBLE' => '10 to 18 days',
            'MARITIME' => '30 to 45 days',
        ],
    ],

    'summary' => [
        'discount' => 'Discount',
        'commission' => 'NJ Global Trade commission',
        'vat' => 'VAT',
        'total' => 'Total',
        'total_incl_tax' => 'Total incl. tax',
        'total_paid' => 'Total paid',
        'total_paid_incl_tax' => 'Total paid (incl. tax)',
        'total_credited' => 'Total credited',
        'total_credited_incl_tax' => 'Total credited (incl. tax)',
        'credited_subtotal_excl_tax' => 'Credited subtotal (excl. tax)',
    ],

    'currency' => [
        'multi_label' => 'Total amount expressed in several currencies',
        'reference' => 'reference currency',
        'equiv_note_due' => 'Amount due to the company in the order currency (:code) — other currencies are equivalences frozen at the issue-day rate.',
        'equiv_note_paid' => 'Amount settled in the order currency (:code) — other currencies are equivalences frozen at the issue-day rate.',
    ],

    'proforma' => [
        'title' => 'PROFORMA INVOICE',
        'title_comparatif' => 'PROFORMA INVOICE — COMPARISON',
        'subtitle' => 'This document is a quotation — it is not an invoice',
    ],

    'invoice' => [
        'title' => 'INVOICE',
        'subtitle' => 'Final invoice — issued after full payment',
    ],

    'credit_note' => [
        'title' => 'CREDIT NOTE',
        'subtitle' => 'Credit note',
        'credited_line' => 'This credit note credits document :number (:type issued on :date).',
        'type_facture' => 'invoice',
        'type_proforma' => 'proforma',
    ],

    'receipt' => [
        'title' => 'RECEIPT',
        'subtitle' => 'Official payment receipt',
        'amount_received' => 'Amount received',
        'payment_method' => 'Payment method',
        'payment_date' => 'Payment date',
        'receipt_number' => 'Receipt no.',
        'transaction_ref' => 'Transaction reference',
    ],

    'stamp' => [
        'paid_in_full' => 'Paid in full',
        'paid' => 'Paid',
    ],

    'payment_method' => [
        'ORANGE_MONEY' => 'Orange Money',
        'VIREMENT_UBA' => 'Bank transfer (UBA)',
        'WAVE' => 'Wave',
        'MTN_MOMO' => 'MTN MoMo',
        'ESPECES' => 'Cash',
        'AUTRE' => 'Other',
    ],

    'conclusion' => [
        'terms_validity' => 'Terms & validity',
        'terms' => 'Terms',
        'settlement_receipt' => 'Settlement receipt',
        'payment_receipt' => 'Payment receipt',
        'thanks' => 'Thank you for your trust — for any question, contact us on WhatsApp or by email.',
    ],

    'comparatif' => [
        'client_info' => 'Client information',
        'client_name' => 'Client name',
        'country' => 'Country',
        'phone' => 'Phone',
        'company' => 'Company',
        'address_city' => 'Address / City',
        'product_need' => 'Product / need',
        'product_name' => 'Product name',
        'description' => 'Description / specifications',
        'package_type' => 'Package type',
        'package_image_placeholder' => 'PRODUCT IMAGE PLACEHOLDER',
        'package_standard' => 'Standard',
        'package_sensitive' => 'Sensitive / Battery',
        'options_comparison' => 'Options comparison',
        'criteria' => 'Criteria',
        'level' => 'Level',
        'moq' => 'Minimum quantity (MOQ)',
        'quantity_ordered' => 'Quantity ordered',
        'recommendation' => 'Recommendation',
        'professional_advice' => 'Professional advice',
        'option' => 'Option',
        'parameters' => 'Parameters',
        'estimate' => 'Estimate',
        'air' => 'Air',
        'sea' => 'Sea',
        'lead' => 'Lead time',
        'rate' => 'Rate',
        'estimated_cost' => 'Estimated cost',
        'unavailable_air' => 'Unavailable — the order has no estimated weight, or no active applicable rate.',
        'unavailable_sea' => 'Unavailable — the order has no estimated volume, or no active applicable rate.',
        'details_advantages' => 'Details & advantages',
        'strengths_for' => 'Strengths — :option',
        'attention_points' => 'Points of attention',
        'not_provided' => 'Not provided.',
        'notes_conditions' => 'Notes / conditions',
        'commercial_terms' => 'Commercial terms',
        'production_lead' => 'Production lead time',
        'payment' => 'Payment',
        'customs_delivery' => 'Customs / delivery',
    ],

    'legal' => [
        'proforma' => 'This document is a quotation (proforma) — it is not an invoice or a receipt. The weights and volumes shown are indicative, within a ±10 to 15% margin; final values will be confirmed at shipment. :validity_sentenceThe order is considered confirmed upon receipt of a deposit or of full payment, as agreed with our team. An official receipt will be issued once your payment is received.',
        'proforma_validity' => 'This document remains valid until :due. ',
        'invoice' => 'Invoice issued automatically after full payment of the amount due (NJ Global Trade specification, section 2.2). This document evidences full settlement of the order with our company. The weights and volumes shown remain indicative until shipment, within a ±10 to 15% margin. Please keep this document; it may be requested for any follow-up on your order.',
        'receipt' => 'Official payment receipt (NJ Global Trade specification, section 2.2). This document evidences receipt of the payment shown above and serves as proof of payment with our company. A final invoice is also issued to you. Please keep this receipt; it may be requested for any follow-up on your order.',
        'credit_note' => 'This credit note cancels all or part of document :number. It is deducted from the amount still due on the related order and does not trigger an automatic refund. An actual refund, if any, is recorded separately (a REFUND-type payment).',
    ],

];
